# Generated by Django 4.2.11 on 2024-03-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loginpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="user_type",
            field=models.CharField(default="junior", max_length=10),
        ),
    ]
