# Generated by Django 4.2.11 on 2024-03-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loginpage", "0002_userinfo_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(default="<123@gmail.com>", max_length=254),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="user_type",
            field=models.CharField(default="annotator", max_length=10),
        ),
    ]
