# Generated by Django 4.2.11 on 2024-04-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loginpage", "0003_userinfo_age_userinfo_email_alter_userinfo_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="user_type",
            field=models.CharField(default="annotator", max_length=20),
        ),
    ]
