# Generated by Django 4.2.11 on 2024-04-05 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loginpage", "0004_alter_userinfo_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="user_type",
        ),
    ]
