# Generated by Django 4.2.11 on 2024-03-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="myname",
            field=models.CharField(default="", max_length=32),
        ),
    ]
