# Generated by Django 4.2.11 on 2024-04-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0002_file_myname"),
    ]

    operations = [
        migrations.CreateModel(
            name="project_level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=50)),
                ("level_set", models.IntegerField(default=1)),
            ],
        ),
    ]
