# Generated by Django 4.2.11 on 2024-04-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0003_project_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_level",
            name="annotator_name",
            field=models.CharField(default="", max_length=32),
        ),
    ]
