# Generated by Django 4.2.11 on 2024-04-22 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0004_project_level_annotator_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_level",
            name="project_start_date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 22, 7, 49, 39, 135943)
            ),
        ),
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_change_date",
                    models.DateField(default=datetime.datetime.now),
                ),
                (
                    "annotaor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="juniorpage.project_level",
                    ),
                ),
            ],
        ),
    ]
