# Generated by Django 4.2.11 on 2024-04-22 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0005_project_level_project_start_date_todolist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_level",
            name="project_start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
