# Generated by Django 4.2.11 on 2024-04-22 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0006_alter_project_level_project_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_level",
            name="project_start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="project_change_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
