# Generated by Django 4.2.11 on 2024-04-26 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0007_alter_project_level_project_start_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="detail_file_of_project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(default="", max_length=32)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="juniorpage.project_level",
                    ),
                ),
            ],
        ),
    ]
