# Generated by Django 4.2.11 on 2024-04-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0008_detail_file_of_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail_file_of_project",
            name="project",
        ),
        migrations.AddField(
            model_name="detail_file_of_project",
            name="annotator_name",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="detail_file_of_project",
            name="level_set",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="detail_file_of_project",
            name="project_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
