# Generated by Django 4.2.11 on 2024-05-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0010_detail_file_of_project_folder_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail_file_of_project",
            name="folder_name",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="annotaor",
        ),
        migrations.AddField(
            model_name="detail_file_of_project",
            name="people_sent",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="todolist",
            name="annotator_name",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="todolist",
            name="file_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="todolist",
            name="people_sent",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="todolist",
            name="project_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
