# Generated by Django 4.2.11 on 2024-05-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juniorpage", "0011_remove_detail_file_of_project_folder_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail_file_of_project",
            name="folder_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
