# Generated by Django 4.2.11 on 2024-04-05 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_level", models.IntegerField(default=2)),
                ("project_max_tasks", models.IntegerField(default=50)),
                (
                    "project_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_owner_page.project_owner",
                    ),
                ),
            ],
        ),
    ]
