# Generated by Django 4.2.11 on 2024-04-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0002_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_owner",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
