# Generated by Django 4.2.11 on 2024-04-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0003_alter_project_owner_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_owner",
            name="project_level",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="project_owner",
            name="project_max_tasks",
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
