# Generated by Django 4.2.11 on 2024-04-08 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0006_alter_project_owner_project_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project_owner",
            name="project_level",
        ),
        migrations.RemoveField(
            model_name="project_owner",
            name="project_max_tasks",
        ),
    ]
