# Generated by Django 4.2.11 on 2024-04-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0009_alter_project_owner_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_owner",
            name="folder_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
