# Generated by Django 4.2.11 on 2024-05-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0010_project_owner_folder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="people_sent",
            field=models.CharField(default="", max_length=30),
        ),
    ]
