# Generated by Django 4.2.11 on 2024-05-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0011_todolist_people_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="project_owner",
            field=models.CharField(max_length=30),
        ),
    ]
