# Generated by Django 4.2.11 on 2024-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0012_alter_todolist_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="project_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
