# Generated by Django 4.2.11 on 2024-05-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_owner_page", "0013_todolist_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
